name: Deploy Docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
        config: ${{ secrets.SSH_CONFIG }}

    - run: yarn global add vuepress
    - run: yarn global bin
    - run: /home/runner/.yarn/bin/vuepress build
    - run: rsync -av --exclude=.git .vuepress/dist/ homestack:/var/www/homestack.dev/
